import turtle
def countdown(color):
    countdown=turtle.Turtle()
    countdown.color(color)
    countdown.speed(100)
    countdown.penup()
    countdown.left(90)
    countdown.forward(1000)
    countdown.left(90)
    countdown.forward(150)
    countdown.pendown()
    countdown.right(210)
    countdown.circle(50,210)
    countdown.right(180)
    countdown.circle(50,210)
    countdown.penup()
    countdown.right(-60)
    countdown.forward(190)
    countdown.left(90)
    countdown.forward(120)
    countdown.pendown()
    countdown.forward(100)
    countdown.backward(100)
    countdown.left(55)
    countdown.forward(150)
    countdown.circle(50,200)
    countdown.penup()
    countdown.left(15)
    countdown.forward(165)
    countdown.left(90)
    countdown.forward(140)
    countdown.pendown()
    countdown.forward(100)
    countdown.backward(50)
    countdown.left(90)
    countdown.forward(200)
    countdown.left(135)
    countdown.forward(2000)
    countdown.penup()
    countdown.color("white")
    countdown.forward(1)
def A(color,number):
    aiden=turtle.Turtle()
    aiden.speed(100)
    aiden.color(color)
    aiden.penup()
    if number<14: #if the index is less than 14, move up two lines
        aiden.forward(-650+number*95)
        aiden.right(90)
        aiden.forward(-240)
        aiden.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        aiden.forward(-1980+number*95)
        aiden.right(90)
        aiden.forward(-120)
        aiden.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        aiden.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        aiden.forward(-4640+number*95)
        aiden.right(90)
        aiden.forward(120)
        aiden.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        aiden.forward(-5970+number*95)
        aiden.right(90)
        aiden.forward(240)
        aiden.left(90)
    aiden.pendown()
    aiden.left(69)
    aiden.forward(53)
    aiden.right(69)
    aiden.forward(37)
    aiden.backward(37)
    aiden.left(69)
    aiden.forward(53)
    aiden.right(139)
    aiden.forward(107)
    aiden.penup()
    aiden.color("white")
    aiden.right(90)
    aiden.forward(3)
def B(color,number):
    bob=turtle.Turtle()
    bob.speed(100)
    bob.color(color)
    bob.penup()
    if number<14: #if the index is less than 14, move up two lines
        bob.forward(-650+number*95)
        bob.right(90)
        bob.forward(-240)
        bob.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        bob.forward(-1980+number*95)
        bob.right(90)
        bob.forward(-120)
        bob.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        bob.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        bob.forward(-4640+number*95)
        bob.right(90)
        bob.forward(120)
        bob.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        bob.forward(-5970+number*95)
        bob.right(90)
        bob.forward(240)
        bob.left(90)
    bob.pendown()
    bob.left(90)
    bob.forward(100)
    bob.right(-90)
    bob.forward(-50)
    bob.circle(25,-180)
    bob.forward(-50)
    bob.penup()
    bob.forward(50)
    bob.right(180)
    bob.forward(50)
    bob.pendown()
    bob.forward(-50)
    bob.circle(25,-180)
    bob.forward(-50)
    bob.penup()
    bob.color("white")
    bob.backward(3)
def C(color,number):
    collin=turtle.Turtle()
    collin.speed(100)
    collin.color(color)
    collin.penup()
    if number<14: #if the index is less than 14, move up two lines
        collin.forward(-650+number*95)
        collin.right(90)
        collin.forward(-240)
        collin.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        collin.forward(-1980+number*95)
        collin.right(90)
        collin.forward(-120)
        collin.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        collin.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        collin.forward(-4640+number*95)
        collin.right(90)
        collin.forward(120)
        collin.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        collin.forward(-5970+number*95)
        collin.right(90)
        collin.forward(240)
        collin.left(90)
    collin.forward(75)
    collin.left(90)
    collin.forward(58)
    collin.pendown()
    collin.circle(40,180)
    collin.forward(20)
    collin.circle(40,180)
    collin.penup()
    collin.color("white")
    collin.forward(1)
def D(color,number):
    donald=turtle.Turtle()
    donald.color(color)
    donald.speed(100)
    donald.penup()
    if number<14: #if the index is less than 14, move up two lines
        donald.forward(-650+number*95)
        donald.right(90)
        donald.forward(-240)
        donald.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        donald.forward(-1980+number*95)
        donald.right(90)
        donald.forward(-120)
        donald.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        donald.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        donald.forward(-4640+number*95)
        donald.right(90)
        donald.forward(120)
        donald.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        donald.forward(-5970+number*95)
        donald.right(90)
        donald.forward(240)
        donald.left(90)
    donald.pendown()
    donald.left(90)
    donald.forward(100)
    donald.backward(100)
    donald.right(90)
    donald.forward(40)
    donald.circle(43,90)
    donald.forward(15)
    donald.circle(42,90)
    donald.forward(41)
    donald.penup()
    donald.color("white")
    donald.left(90)
    donald.backward(1)
def E(color,number):
    eli=turtle.Turtle()
    eli.color(color)
    eli.speed(100)
    eli.penup()
    if number<14: #if the index is less than 14, move up two lines
        eli.forward(-650+number*95)
        eli.right(90)
        eli.forward(-240)
        eli.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        eli.forward(-1980+number*95)
        eli.right(90)
        eli.forward(-120)
        eli.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        eli.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        eli.forward(-4640+number*95)
        eli.right(90)
        eli.forward(120)
        eli.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        eli.forward(-5970+number*95)
        eli.right(90)
        eli.forward(240)
        eli.left(90)
    eli.pendown()
    eli.forward(80)
    eli.backward(80)
    eli.left(90)
    eli.forward(50)
    eli.right(90)
    eli.forward(80)
    eli.backward(80)
    eli.left(90)
    eli.forward(50)
    eli.right(90)
    eli.forward(80)
    eli.color("white")
    eli.penup()
    eli.forward(1)
def F(color,number):
    frank=turtle.Turtle()
    frank.speed(100)
    frank.color(color)
    frank.penup()
    if number<14: #if the index is less than 14, move up two lines
        frank.forward(-650+number*95)
        frank.right(90)
        frank.forward(-240)
        frank.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        frank.forward(-1980+number*95)
        frank.right(90)
        frank.forward(-120)
        frank.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        frank.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        frank.forward(-4640+number*95)
        frank.right(90)
        frank.forward(120)
        frank.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        frank.forward(-5970+number*95)
        frank.right(90)
        frank.forward(240)
        frank.left(90)
    frank.pendown()
    frank.left(90)
    frank.forward(50)
    frank.right(90)
    frank.forward(60)
    frank.backward(60)
    frank.left(90)
    frank.forward(50)
    frank.right(90)
    frank.forward(80)
    frank.penup()
    frank.color("white")
    frank.forward(1)
def G(color,number):
    greg=turtle.Turtle()
    greg.speed(100)
    greg.color(color)
    greg.penup()
    if number<14: #if the index is less than 14, move up two lines
        greg.forward(-650+number*95)
        greg.right(90)
        greg.forward(-240)
        greg.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        greg.forward(-1980+number*95)
        greg.right(90)
        greg.forward(-120)
        greg.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        greg.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        greg.forward(-4640+number*95)
        greg.right(90)
        greg.forward(120)
        greg.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        greg.forward(-5970+number*95)
        greg.right(90)
        greg.forward(240)
        greg.left(90)
    greg.forward(50)
    greg.left(90)
    greg.forward(50)
    greg.pendown()
    greg.right(90)
    greg.forward(30)
    greg.left(90)
    greg.backward(5)
    greg.circle(45,-180)
    greg.backward(10)
    greg.circle(45,-90)
    greg.backward(5)
    greg.circle(45,-45)
    greg.penup()
    greg.color("white")
    greg.backward(1)
def H(color,number):
    hank=turtle.Turtle()
    hank.speed(100)
    hank.color(color)
    hank.penup()
    if number<14: #if the index is less than 14, move up two lines
        hank.forward(-650+number*95)
        hank.right(90)
        hank.forward(-240)
        hank.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        hank.forward(-1980+number*95)
        hank.right(90)
        hank.forward(-120)
        hank.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        hank.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        hank.forward(-4640+number*95)
        hank.right(90)
        hank.forward(120)
        hank.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        hank.forward(-5970+number*95)
        hank.right(90)
        hank.forward(240)
        hank.left(90)
    hank.pendown()
    hank.left(90)
    hank.forward(100)
    hank.backward(50)
    hank.right(90)
    hank.forward(80)
    hank.left(90)
    hank.forward(50)
    hank.backward(100)
    hank.penup()
    hank.color("white")
    hank.backward(1)
def I(color,number):
    ike=turtle.Turtle()
    ike.speed(100)
    ike.color(color)
    ike.penup()
    if number<14: #if the index is less than 14, move up two lines
        ike.forward(-650+number*95)
        ike.right(90)
        ike.forward(-240)
        ike.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        ike.forward(-1980+number*95)
        ike.right(90)
        ike.forward(-120)
        ike.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        ike.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        ike.forward(-4640+number*95)
        ike.right(90)
        ike.forward(120)
        ike.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        ike.forward(-5970+number*95)
        ike.right(90)
        ike.forward(240)
        ike.left(90)
    ike.pendown()
    ike.forward(90)
    ike.backward(45)
    ike.left(90)
    ike.forward(100)
    ike.left(90)
    ike.forward(45)
    ike.backward(90)
    ike.penup()
    ike.color("white")
    ike.forward(1)
def J(color,number):
    jake=turtle.Turtle()
    jake.speed(100)
    jake.color(color)
    jake.penup()
    if number<14: #if the index is less than 14, move up two lines
        jake.forward(-650+number*95)
        jake.right(90)
        jake.forward(-240)
        jake.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        jake.forward(-1980+number*95)
        jake.right(90)
        jake.forward(-120)
        jake.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        jake.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        jake.forward(-4640+number*95)
        jake.right(90)
        jake.forward(120)
        jake.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        jake.forward(-5970+number*95)
        jake.right(90)
        jake.forward(240)
        jake.left(90)
    jake.right(90)
    jake.backward(100)
    jake.left(90)
    jake.forward(25)
    jake.pendown()
    jake.forward(60)
    jake.backward(30)
    jake.right(90)
    jake.forward(70)
    jake.right(180)
    jake.circle(30,-180)
    jake.penup()
    jake.color("white")
    jake.forward(1)
def K(color,number):
    kate=turtle.Turtle()
    kate.speed(100)
    kate.color(color)
    kate.penup()
    if number<14: #if the index is less than 14, move up two lines
        kate.forward(-650+number*95)
        kate.right(90)
        kate.forward(-240)
        kate.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        kate.forward(-1980+number*95)
        kate.right(90)
        kate.forward(-120)
        kate.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        kate.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        kate.forward(-4640+number*95)
        kate.right(90)
        kate.forward(120)
        kate.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        kate.forward(-5970+number*95)
        kate.right(90)
        kate.forward(240)
        kate.left(90)
    kate.pendown()
    kate.left(90)
    kate.forward(100)
    kate.backward(50)
    kate.right(58)
    kate.forward(94)
    kate.backward(94)
    kate.right(64)
    kate.forward(94)
    kate.penup()
    kate.color("white")
    kate.forward(20)
def L(color,number):
    leigh=turtle.Turtle()
    leigh.speed(100)
    leigh.color(color)
    leigh.penup()
    if number<14: #if the index is less than 14, move up two lines
        leigh.forward(-650+number*95)
        leigh.right(90)
        leigh.forward(-240)
        leigh.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        leigh.forward(-1980+number*95)
        leigh.right(90)
        leigh.forward(-120)
        leigh.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        leigh.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        leigh.forward(-4640+number*95)
        leigh.right(90)
        leigh.forward(120)
        leigh.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        leigh.forward(-5970+number*95)
        leigh.right(90)
        leigh.forward(240)
        leigh.left(90)
    leigh.pendown()
    leigh.forward(80)
    leigh.backward(80)
    leigh.left(90)
    leigh.forward(105)
    leigh.penup()
    leigh.color("white")
    leigh.forward(1)
def M(color,number):
    mallory=turtle.Turtle()
    mallory.speed(100)
    mallory.color(color)
    mallory.penup()
    if number<14: #if the index is less than 14, move up two lines
        mallory.forward(-650+number*95)
        mallory.right(90)
        mallory.forward(-240)
        mallory.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        mallory.forward(-1980+number*95)
        mallory.right(90)
        mallory.forward(-120)
        mallory.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        mallory.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        mallory.forward(-4640+number*95)
        mallory.right(90)
        mallory.forward(120)
        mallory.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        mallory.forward(-5970+number*95)
        mallory.right(90)
        mallory.forward(240)
        mallory.left(90)
    mallory.pendown()
    mallory.left(90)
    mallory.forward(100)
    mallory.right(158)
    mallory.forward(108)
    mallory.left(136)
    mallory.forward(108)
    mallory.right(158)
    mallory.forward(100)
    mallory.penup()
    mallory.color("white")
    mallory.forward(10)
def N(color,number):
    nestor=turtle.Turtle()
    nestor.speed(100)
    nestor.color(color)
    nestor.penup()
    if number<14: #if the index is less than 14, move up two lines
        nestor.forward(-650+number*95)
        nestor.right(90)
        nestor.forward(-240)
        nestor.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        nestor.forward(-1980+number*95)
        nestor.right(90)
        nestor.forward(-120)
        nestor.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        nestor.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        nestor.forward(-4640+number*95)
        nestor.right(90)
        nestor.forward(120)
        nestor.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        nestor.forward(-5970+number*95)
        nestor.right(90)
        nestor.forward(240)
        nestor.left(90)
    nestor.pendown()
    nestor.left(90)
    nestor.forward(100)
    nestor.right(141)
    nestor.forward(128)
    nestor.left(141)
    nestor.forward(100)
    nestor.penup()
    nestor.color("white")
    nestor.forward(5)
def O(color,number):
    oliver=turtle.Turtle()
    oliver.speed(100)
    oliver.color(color)
    oliver.penup()
    if number<14: #if the index is less than 14, move up two lines
        oliver.forward(-650+number*95)
        oliver.right(90)
        oliver.forward(-240)
        oliver.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        oliver.forward(-1980+number*95)
        oliver.right(90)
        oliver.forward(-120)
        oliver.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        oliver.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        oliver.forward(-4640+number*95)
        oliver.right(90)
        oliver.forward(120)
        oliver.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        oliver.forward(-5970+number*95)
        oliver.right(90)
        oliver.forward(240)
        oliver.left(90)
    oliver.forward(35)
    oliver.pendown()
    oliver.circle(40,90)
    oliver.forward(20)
    oliver.circle(40,180)
    oliver.forward(20)
    oliver.circle(40,90)
    oliver.penup()
    oliver.color("white")
    oliver.left(90)
    oliver.forward(20)
def P(color,number):
    piper=turtle.Turtle()
    piper.speed(100)
    piper.color(color)
    piper.penup()
    if number<14: #if the index is less than 14, move up two lines
        piper.forward(-650+number*95)
        piper.right(90)
        piper.forward(-240)
        piper.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        piper.forward(-1980+number*95)
        piper.right(90)
        piper.forward(-120)
        piper.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        piper.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        piper.forward(-4640+number*95)
        piper.right(90)
        piper.forward(120)
        piper.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        piper.forward(-5970+number*95)
        piper.right(90)
        piper.forward(240)
        piper.left(90)
    piper.pendown()
    piper.left(90)
    piper.forward(100)
    piper.backward(50)
    piper.right(90)
    piper.forward(50)
    piper.circle(25,180)
    piper.forward(50)
    piper.penup()
    piper.color("white")
    piper.left(145)
    piper.forward(20)
def Q(color,number):
    quinn=turtle.Turtle()
    quinn.speed(100)
    quinn.color(color)
    quinn.penup()
    if number<14: #if the index is less than 14, move up two lines
        quinn.forward(-650+number*95)
        quinn.right(90)
        quinn.forward(-240)
        quinn.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        quinn.forward(-1980+number*95)
        quinn.right(90)
        quinn.forward(-120)
        quinn.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        quinn.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        quinn.forward(-4640+number*95)
        quinn.right(90)
        quinn.forward(120)
        quinn.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        quinn.forward(-5970+number*95)
        quinn.right(90)
        quinn.forward(240)
        quinn.left(90)
    quinn.forward(35)
    quinn.pendown()
    quinn.circle(40,90)
    quinn.forward(20)
    quinn.circle(40,180)
    quinn.forward(20)
    quinn.circle(40,90)
    quinn.penup()
    quinn.left(90)
    quinn.forward(35)
    quinn.pendown()
    quinn.right(135)
    quinn.forward(49)
    quinn.penup()
    quinn.right(180)
    quinn.color("white")
    quinn.forward(60)
def R(color,number):
    richard=turtle.Turtle()
    richard.speed(100)
    richard.color(color)
    richard.penup()
    if number<14: #if the index is less than 14, move up two lines
        richard.forward(-650+number*95)
        richard.right(90)
        richard.forward(-240)
        richard.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        richard.forward(-1980+number*95)
        richard.right(90)
        richard.forward(-120)
        richard.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        richard.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        richard.forward(-4640+number*95)
        richard.right(90)
        richard.forward(120)
        richard.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        richard.forward(-5970+number*95)
        richard.right(90)
        richard.forward(240)
        richard.left(90)
    richard.pendown()
    richard.left(90)
    richard.forward(100)
    richard.backward(50)
    richard.right(90)
    richard.forward(50)
    richard.circle(25,180)
    richard.forward(50)
    richard.left(90)
    richard.forward(50)
    richard.left(56)
    richard.forward(90)
    richard.penup()
    richard.color("white")
    richard.left(160)
    richard.forward(50)
def S(color,number):
    samantha=turtle.Turtle()
    samantha.speed(100)
    samantha.color(color)
    samantha.penup()
    if number<14: #if the index is less than 14, move up two lines
        samantha.forward(-650+number*95)
        samantha.right(90)
        samantha.forward(-240)
        samantha.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        samantha.forward(-1980+number*95)
        samantha.right(90)
        samantha.forward(-120)
        samantha.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        samantha.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        samantha.forward(-4640+number*95)
        samantha.right(90)
        samantha.forward(120)
        samantha.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        samantha.forward(-5970+number*95)
        samantha.right(90)
        samantha.forward(240)
        samantha.left(90)
    samantha.pendown()
    samantha.forward(50)
    samantha.circle(25,180)
    samantha.forward(25)
    samantha.right(180)
    samantha.circle(25,-180)
    samantha.right(180)
    samantha.forward(50)
    samantha.right(95)
    samantha.penup()
    samantha.color("white")
    samantha.forward(20)
def T(color,number):
    tim=turtle.Turtle()
    tim.speed(100)
    tim.color(color)
    tim.penup()
    if number<14: #if the index is less than 14, move up two lines
        tim.forward(-650+number*95)
        tim.right(90)
        tim.forward(-240)
        tim.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        tim.forward(-1980+number*95)
        tim.right(90)
        tim.forward(-120)
        tim.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        tim.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        tim.forward(-4640+number*95)
        tim.right(90)
        tim.forward(120)
        tim.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        tim.forward(-5970+number*95)
        tim.right(90)
        tim.forward(240)
        tim.left(90)
    tim.forward(40)
    tim.pendown()
    tim.left(90)
    tim.forward(100)
    tim.left(90)
    tim.forward(40)
    tim.backward(80)
    tim.penup()
    tim.color("white")
    tim.left(45)
    tim.forward(20)
def U(color,number):
    ulysseus=turtle.Turtle()
    ulysseus.speed(100)
    ulysseus.color(color)
    ulysseus.penup()
    if number<14: #if the index is less than 14, move up two lines
        ulysseus.forward(-650+number*95)
        ulysseus.right(90)
        ulysseus.forward(-240)
        ulysseus.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        ulysseus.forward(-1980+number*95)
        ulysseus.right(90)
        ulysseus.forward(-120)
        ulysseus.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        ulysseus.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        ulysseus.forward(-4640+number*95)
        ulysseus.right(90)
        ulysseus.forward(120)
        ulysseus.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        ulysseus.forward(-5970+number*95)
        ulysseus.right(90)
        ulysseus.forward(240)
        ulysseus.left(90)
    ulysseus.left(90)
    ulysseus.forward(100)
    ulysseus.pendown()
    ulysseus.left(180)
    ulysseus.forward(60)
    ulysseus.circle(40,180)
    ulysseus.forward(60)
    ulysseus.left(135)
    ulysseus.color("white")
    ulysseus.forward(30)
def V(color,number):
    victor=turtle.Turtle()
    victor.speed(100)
    victor.color(color)
    victor.penup()
    if number<14: #if the index is less than 14, move up two lines
        victor.forward(-650+number*95)
        victor.right(90)
        victor.forward(-240)
        victor.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        victor.forward(-1980+number*95)
        victor.right(90)
        victor.forward(-120)
        victor.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        victor.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        victor.forward(-4640+number*95)
        victor.right(90)
        victor.forward(120)
        victor.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        victor.forward(-5970+number*95)
        victor.right(90)
        victor.forward(240)
        victor.left(90)
    victor.left(90)
    victor.forward(100)
    victor.pendown()
    victor.right(158)
    victor.forward(108)
    victor.left(136)
    victor.forward(108)
    victor.left(160)
    victor.color("white")
    victor.penup()
    victor.forward(40)
def W(color,number):
    william=turtle.Turtle()
    william.speed(100)
    william.color(color)
    william.penup()
    if number<14: #if the index is less than 14, move up two lines
        william.forward(-650+number*95)
        william.right(90)
        william.forward(-240)
        william.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        william.forward(-1980+number*95)
        william.right(90)
        william.forward(-120)
        william.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        william.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        william.forward(-4640+number*95)
        william.right(90)
        william.forward(120)
        william.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        william.forward(-5970+number*95)
        william.right(90)
        william.forward(240)
        william.left(90)
    william.left(90)
    william.forward(100)
    william.pendown()
    william.right(165)
    william.forward(104)
    william.left(150)
    william.forward(52)
    william.right(150)
    william.forward(52)
    william.left(150)
    william.forward(104)
    william.left(165)
    william.penup()
    william.color("white")
    william.forward(40)
def X(color,number):
    xavier=turtle.Turtle()
    xavier.speed(100)
    xavier.color(color)
    xavier.penup()
    if number<14: #if the index is less than 14, move up two lines
        xavier.forward(-650+number*95)
        xavier.right(90)
        xavier.forward(-240)
        xavier.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        xavier.forward(-1980+number*95)
        xavier.right(90)
        xavier.forward(-120)
        xavier.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        xavier.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        xavier.forward(-4640+number*95)
        xavier.right(90)
        xavier.forward(120)
        xavier.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        xavier.forward(-5970+number*95)
        xavier.right(90)
        xavier.forward(240)
        xavier.left(90)
    xavier.left(90)
    xavier.forward(100)
    xavier.pendown()
    xavier.right(141)
    xavier.forward(128)
    xavier.penup()
    xavier.left(141)
    xavier.forward(100)
    xavier.pendown()
    xavier.left(141)
    xavier.forward(128)
    xavier.penup()
    xavier.color("white")
    xavier.left(160)
    xavier.forward(40)
def Y(color,number):
    yasmine=turtle.Turtle()
    yasmine.speed(100)
    yasmine.color(color)
    yasmine.penup()
    if number<14: #if the index is less than 14, move up two lines
        yasmine.forward(-650+number*95)
        yasmine.right(90)
        yasmine.forward(-240)
        yasmine.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        yasmine.forward(-1980+number*95)
        yasmine.right(90)
        yasmine.forward(-120)
        yasmine.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        yasmine.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        yasmine.forward(-4640+number*95)
        yasmine.right(90)
        yasmine.forward(120)
        yasmine.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        yasmine.forward(-5970+number*95)
        yasmine.right(90)
        yasmine.forward(240)
        yasmine.left(90)
    yasmine.forward(40)
    yasmine.pendown()
    yasmine.left(90)
    yasmine.forward(50)
    yasmine.right(39)
    yasmine.forward(64)
    yasmine.backward(64)
    yasmine.left(78)
    yasmine.forward(64)
    yasmine.penup()
    yasmine.color("white")
    yasmine.right(150)
    yasmine.forward(40)
def Z(color,number):
    zayan=turtle.Turtle()
    zayan.speed(100)
    zayan.color(color)
    zayan.penup()
    if number<14: #if the index is less than 14, move up two lines
        zayan.forward(-650+number*95)
        zayan.right(90)
        zayan.forward(-240)
        zayan.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        zayan.forward(-1980+number*95)
        zayan.right(90)
        zayan.forward(-120)
        zayan.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        zayan.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        zayan.forward(-4640+number*95)
        zayan.right(90)
        zayan.forward(120)
        zayan.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        zayan.forward(-5970+number*95)
        zayan.right(90)
        zayan.forward(240)
        zayan.left(90)
    zayan.pendown()
    zayan.forward(80)
    zayan.backward(80)
    zayan.left(51)
    zayan.forward(128)
    zayan.left(129)
    zayan.forward(80)
    zayan.penup()
    zayan.color("white")
    zayan.right(150)
    zayan.forward(20)
def period(color,number):
    period=turtle.Turtle()
    period.speed(100)
    period.color(color)
    period.penup()
    if number<14: #if the index is less than 14, move up two lines
        period.forward(-650+number*95)
        period.right(90)
        period.forward(-240)
        period.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        period.forward(-1980+number*95)
        period.right(90)
        period.forward(-120)
        period.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        period.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        period.forward(-4640+number*95)
        period.right(90)
        period.forward(120)
        period.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        period.forward(-5970+number*95)
        period.right(90)
        period.forward(240)
        period.left(90)
    period.pendown()
    period.begin_fill()
    period.circle(10)
    period.end_fill()
    period.left(90)
    period.forward(12)
def eMark(color,number):
    eMark=turtle.Turtle()
    eMark.speed(100)
    eMark.color(color)
    eMark.penup()
    if number<14: #if the index is less than 14, move up two lines
        eMark.forward(-650+number*95)
        eMark.right(90)
        eMark.forward(-240)
        eMark.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        eMark.forward(-1980+number*95)
        eMark.right(90)
        eMark.forward(-120)
        eMark.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        eMark.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        eMark.forward(-4640+number*95)
        eMark.right(90)
        eMark.forward(120)
        eMark.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        eMark.forward(-5970+number*95)
        eMark.right(90)
        eMark.forward(240)
        eMark.left(90)
    eMark.pendown()
    eMark.begin_fill()
    eMark.circle(7)
    eMark.end_fill()
    eMark.left(90)
    eMark.penup()
    eMark.forward(30)
    eMark.left(90)
    eMark.forward(7)
    eMark.right(90)
    eMark.begin_fill()
    eMark.pendown()
    eMark.forward(70)
    eMark.right(90)
    eMark.forward(14)
    eMark.right(90)
    eMark.forward(70)
    eMark.right(90)
    eMark.forward(14)
    eMark.end_fill()
    eMark.penup()
    eMark.right(100)
    eMark.forward(40)
def qMark(color,number):
    qMark=turtle.Turtle()
    qMark.speed(100)
    qMark.color(color)
    qMark.penup()
    if number<14: #if the index is less than 14, move up two lines
        qMark.forward(-650+number*95)
        qMark.right(90)
        qMark.forward(-240)
        qMark.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        qMark.forward(-1980+number*95)
        qMark.right(90)
        qMark.forward(-120)
        qMark.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        qMark.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        qMark.forward(-4640+number*95)
        qMark.right(90)
        qMark.forward(120)
        qMark.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        qMark.forward(-5970+number*95)
        qMark.right(90)
        qMark.forward(240)
        qMark.left(90)
    qMark.forward(20)
    qMark.pendown()
    qMark.begin_fill()
    qMark.circle(7)
    qMark.end_fill()
    qMark.left(90)
    qMark.penup()
    qMark.forward(30)
    qMark.pendown()
    qMark.forward(30)
    qMark.right(90)
    qMark.circle(20,270)
    qMark.color("white")
    qMark.penup()
    qMark.forward(20)
def comma(color,number):
    comma=turtle.Turtle()
    comma.speed(100)
    comma.color(color)
    comma.penup()
    if number<14: #if the index is less than 14, move up two lines
        comma.forward(-650+number*95)
        comma.right(90)
        comma.forward(-240)
        comma.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        comma.forward(-1980+number*95)
        comma.right(90)
        comma.forward(-120)
        comma.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        comma.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        comma.forward(-4640+number*95)
        comma.right(90)
        comma.forward(120)
        comma.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        comma.forward(-5970+number*95)
        comma.right(90)
        comma.forward(240)
        comma.left(90)
    comma.forward(10)
    comma.left(90)
    comma.forward(90)
    comma.left(125)
def apostrophe(color,number):
    apostrophe=turtle.Turtle()
    apostrophe.speed(100)
    apostrophe.color(color)
    apostrophe.penup()
    if number<14: #if the index is less than 14, move up two lines
        apostrophe.forward(-650+number*95)
        apostrophe.right(90)
        apostrophe.forward(-240)
        apostrophe.left(90)
    elif 13<number<28: #if index is 14-26, move up one line
        apostrophe.forward(-1980+number*95)
        apostrophe.right(90)
        apostrophe.forward(-120)
        apostrophe.left(90)
    elif 27<number<42: #if index is 15-39, stay on the same line
        apostrophe.forward(-3310+number*95)
    elif 41<number<56: #if index is 38-52, move down one line
        apostrophe.forward(-4640+number*95)
        apostrophe.right(90)
        apostrophe.forward(120)
        apostrophe.left(90)
    elif 55<number<70: #if index is 51-55, move down two lines
        apostrophe.forward(-5970+number*95)
        apostrophe.right(90)
        apostrophe.forward(240)
        apostrophe.left(90)
    apostrophe.forward(40)
    apostrophe.left(90)
    apostrophe.forward(80)
    apostrophe.right(35)
    apostrophe.pendown()
    apostrophe.circle(20,60)
    apostrophe.begin_fill()
    apostrophe.circle(5)
    apostrophe.end_fill()
    apostrophe.penup()
    apostrophe.color("white")
    apostrophe.forward(20)
    apostrophe.left(180)
    apostrophe.pendown()
    apostrophe.circle(20,60)
    apostrophe.begin_fill()
    apostrophe.circle(5)
    apostrophe.end_fill()
    apostrophe.penup()
    apostrophe.color("white")
    apostrophe.forward(20)
def space(number):
    susan=turtle.Turtle()
def main():
    #it can go up to index 69, new lines start at 0, 14, 28, 42, and 56
    countdown("purple")
    countdown("purple")
    #format as     capital letter/puntuation mark("color",position)
    E("blue",0)
    X("blue",1)
    A("blue",2)
    M("blue",3)
    P("red",4)
    L("red",5)
    E("orange",6)
main()
